apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: monitoring
spec:
  ports:
    - port: 8000
  selector:
    app: python-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: python-prometheus-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
